"""remove a column

Revision ID: 0539731b1f36
Revises: 90b544c86145
Create Date: 2022-09-18 13:49:59.085472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0539731b1f36'
down_revision = '90b544c86145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'user', ['owner_id'], ['id'])
    op.add_column('user', sa.Column('avatar_path', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_path')
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
