"""remove a column

Revision ID: 90b544c86145
Revises: caa2c4f92ed9
Create Date: 2022-09-18 13:47:09.142157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b544c86145'
down_revision = 'caa2c4f92ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'user', ['owner_id'], ['id'])
    op.add_column('user', sa.Column('avatar_path', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_path')
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
