"""newMigration

Revision ID: caa2c4f92ed9
Revises: 82a0ebd20457
Create Date: 2022-09-18 13:41:38.575717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa2c4f92ed9'
down_revision = '82a0ebd20457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'user', ['owner_id'], ['id'])
    op.add_column('user', sa.Column('avatar_path', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_path')
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
