"""Source code column

Revision ID: e76b7b37eaae
Revises: c6556ae31496
Create Date: 2022-09-18 22:59:19.717227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76b7b37eaae'
down_revision = 'c6556ae31496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_code_attachment', sa.String(length=9000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('source_code_attachment')

    # ### end Alembic commands ###
